language: ruby
rvm:
  - 2.2.0
addons:
  code_climate:
    repo_token: f511d014eca467c96ab0b049929fda56aeb882cd20d53a117013e399059f0c7d
services:
  - mongodb
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev
script: xvfb-run bundle exec rake
